# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:12.13.0 # Update based on NodeJS LTS version
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm run test:unit
      - run: npm run test:e2e -- --headless
      - run: npm run build
      - run: apt-get install -y zip
      - run: zip -r calchart.zip calchart
      - store_artifacts:
          path: tests/e2e/videos
      - store_artifacts:
          path: calchart.zip
      
