name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/base:12
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run lint:ci
    - run: npm run test:unit
    - run: npm run test:e2e:ci
    - name: Upload e2e videos
      uses: actions/upload-artifact@v2
      with:
        path: tests/e2e/videos/**/*.mp4
    - run: npm run build
    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: calchart
        path: calchart/
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/github-actions' }}
    steps:
    - name: Download build result
      uses: actions/download-artifact@v2
      with:
        name: calchart
        path: calchart/
    - name: Push to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./calchart
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
